import { lightTheme, ThemeProvider } from "@deskpro/deskpro-ui";
import { cleanup, render, waitFor } from "@testing-library/react/";
import React from "react";
import { Main } from "../../src/pages/Main";

const renderPage = () => {
  return render(
    <ThemeProvider theme={lightTheme}>
      <Main />
    </ThemeProvider>
  );
};

jest.mock("../../src/api/api", () => {
  return {
    getFirst5LeadsByContactId: () => ({
      "@odata.context":
        "https://orgefaf8628.api.crm4.dynamics.com/api/data/v9.2/$metadata#leads",
      value: [
        {
          "@odata.etag": 'W/"4788911"',
          prioritycode: 1,
          mobilephone: null,
          merged: false,
          confirminterest: false,
          exchangerate: 1,
          _parentcontactid_value: "80ac35a0-01af-ea11-a812-000d3a8b3ec6",
          decisionmaker: false,
          modifiedon: "2024-01-07T23:36:24Z",
          _owninguser_value: "29c3a361-4b9c-ee11-be36-000d3abf077e",
          address1_shippingmethodcode: 1,
          address1_composite: null,
          lastname: "lol",
          donotpostalmail: false,
          donotphone: false,
          preferredcontactmethodcode: 1,
          _ownerid_value: "29c3a361-4b9c-ee11-be36-000d3abf077e",
          firstname: null,
          jobtitle: null,
          donotemail: false,
          evaluatefit: false,
          yomifullname: "lol",
          address2_addresstypecode: 1,
          address2_shippingmethodcode: 1,
          fullname: "lol",
          address1_addressid: "e2f8071e-ddd0-429b-969f-3c6df5c6436c",
          msdyn_gdproptout: false,
          processid: "00000000-0000-0000-0000-000000000000",
          statuscode: 1,
          createdon: "2024-01-07T23:36:23Z",
          companyname: null,
          donotfax: false,
          leadsourcecode: null,
          versionnumber: 4788911,
          address1_line1: null,
          address1_line2: null,
          donotsendmm: false,
          leadqualitycode: 2,
          _transactioncurrencyid_value: "dbce9d1c-c29c-ee11-be36-000d3abf077e",
          subject: "asd",
          address1_addresstypecode: 1,
          donotbulkemail: false,
          budgetamount_base: 4444444444,
          _modifiedby_value: "29c3a361-4b9c-ee11-be36-000d3abf077e",
          followemail: true,
          leadid: "f4631a11-cd02-45d8-90e2-af33a326cc4e",
          _createdby_value: "29c3a361-4b9c-ee11-be36-000d3abf077e",
          websiteurl: null,
          budgetamount: 4444444444,
          salesstagecode: 1,
          purchasetimeframe: null,
          participatesinworkflow: false,
          statecode: 0,
          _owningbusinessunit_value: "37bca361-4b9c-ee11-be36-000d3abf077e",
          address2_addressid: "31c94f50-8c83-4363-afac-d8b440a0d2d6",
          _customerid_value: "80ac35a0-01af-ea11-a812-000d3a8b3ec6",
          telephone3: null,
          businesscardattributes: null,
          address1_upszone: null,
          address2_city: null,
          _slainvokedid_value: null,
          address1_postofficebox: null,
          importsequencenumber: null,
          utcconversiontimezonecode: null,
          schedulefollowup_qualify: null,
          overriddencreatedon: null,
          stageid: null,
          msdyn_leadscore: null,
          address1_latitude: null,
          address1_utcoffset: null,
          yomifirstname: null,
          estimatedclosedate: null,
          _masterid_value: null,
          lastonholdtime: null,
          address2_fax: null,
          address2_line1: null,
          address1_telephone3: null,
          address1_telephone2: null,
          address1_telephone1: null,
          address2_postofficebox: null,
          emailaddress1: null,
          emailaddress2: null,
          address2_latitude: null,
          emailaddress3: null,
          address2_composite: null,
          salesstage: null,
          traversedpath: null,
          address1_city: null,
          qualificationcomments: null,
          address2_line2: null,
          _msdyn_predictivescoreid_value: null,
          numberofemployees: null,
          teamsfollowed: null,
          address2_stateorprovince: null,
          address2_postalcode: null,
          estimatedamount: null,
          entityimage_url: null,
          initialcommunication: null,
          msdyn_scorehistory: null,
          timezoneruleversionnumber: null,
          estimatedamount_base: null,
          need: null,
          address2_telephone3: null,
          address2_telephone2: null,
          address2_telephone1: null,
          address1_postalcode: null,
          address2_upszone: null,
          _owningteam_value: null,
          budgetstatus: null,
          address2_line3: null,
          timespentbymeonemailandmeetings: null,
          address1_country: null,
          businesscard: null,
          address2_longitude: null,
          _modifiedonbehalfby_value: null,
          revenue_base: null,
          address1_county: null,
          schedulefollowup_prospect: null,
          msdyn_leadscoretrend: null,
          address1_fax: null,
          _createdonbehalfby_value: null,
          _accountid_value: null,
          address2_name: null,
          msdyn_leadgrade: null,
          msdyn_scorereasons: null,
          address2_utcoffset: null,
          _campaignid_value: null,
          sic: null,
          _slaid_value: null,
          fax: null,
          _msdyn_leadkpiid_value: null,
          address2_county: null,
          _qualifyingopportunityid_value: null,
          msdyn_salesassignmentresult: null,
          address1_line3: null,
          industrycode: null,
          address1_stateorprovince: null,
          purchaseprocess: null,
          onholdtime: null,
          entityimage_timestamp: null,
          entityimageid: null,
          _parentaccountid_value: null,
          lastusedincampaign: null,
          _msdyn_segmentid_value: null,
          _originatingcaseid_value: null,
          telephone2: null,
          yomilastname: null,
          revenue: null,
          description: null,
          _relatedobjectid_value: null,
          _contactid_value: null,
          yomimiddlename: null,
          address1_name: null,
          telephone1: null,
          yomicompanyname: null,
          address1_longitude: null,
          entityimage: null,
          middlename: null,
          estimatedvalue: null,
          salutation: null,
          pager: null,
          address2_country: null,
          currency: "EUR",
        },
      ],
    }),
    getFirst5OpportunitiesByContactId: () => ({
      "@odata.context":
        "https://orgefaf8628.api.crm4.dynamics.com/api/data/v9.2/$metadata#opportunities",
      value: [
        {
          "@odata.etag": 'W/"4850455"',
          prioritycode: 1,
          completeinternalreview: false,
          stepname: "1-Qualify",
          filedebrief: false,
          estimatedclosedate: "2024-01-26",
          totalamount: 0,
          confirminterest: false,
          captureproposalfeedback: false,
          exchangerate: 1,
          opportunityid: "f5f084a8-e5e4-40ca-aa6a-9976c04667e1",
          _parentcontactid_value: "80ac35a0-01af-ea11-a812-000d3a8b3ec6",
          identifycompetitors: false,
          _parentaccountid_value: "a4cea450-cb0c-ea11-a813-000d3a1b1223",
          decisionmaker: false,
          totallineitemamount: 0,
          msdyn_forecastcategory: 100000001,
          isrevenuesystemcalculated: false,
          modifiedon: "2024-01-09T02:06:53Z",
          _owninguser_value: "29c3a361-4b9c-ee11-be36-000d3abf077e",
          skippricecalculation: 0,
          presentproposal: false,
          totaldiscountamount: 0,
          _ownerid_value: "29c3a361-4b9c-ee11-be36-000d3abf077e",
          sendthankyounote: false,
          identifycustomercontacts: false,
          name: "Some opportunity",
          evaluatefit: false,
          totalamountlessfreight: 0,
          totalamountlessfreight_base: 0,
          msdyn_gdproptout: false,
          processid: "00000000-0000-0000-0000-000000000000",
          statuscode: 1,
          createdon: "2024-01-09T02:06:50Z",
          customerneed: "David",
          totaltax_base: 0,
          totallineitemamount_base: 0,
          totalamount_base: 0,
          versionnumber: 4850455,
          totallineitemdiscountamount: 0,
          resolvefeedback: false,
          totaltax: 0,
          totaldiscountamount_base: 0,
          _transactioncurrencyid_value: "dbce9d1c-c29c-ee11-be36-000d3abf077e",
          estimatedvalue: 1233,
          estimatedvalue_base: 1233,
          budgetamount_base: 500000,
          _modifiedby_value: "80c5cd80-b1d6-4269-838f-b201cf187868",
          presentfinalproposal: false,
          _createdby_value: "29c3a361-4b9c-ee11-be36-000d3abf077e",
          timezoneruleversionnumber: 4,
          budgetamount: 500000,
          pricingerrorcode: 0,
          salesstagecode: 1,
          totallineitemdiscountamount_base: 0,
          opportunityratingcode: 2,
          identifypursuitteam: false,
          participatesinworkflow: false,
          statecode: 0,
          _owningbusinessunit_value: "37bca361-4b9c-ee11-be36-000d3abf077e",
          pursuitdecision: false,
          developproposal: false,
          _customerid_value: "80ac35a0-01af-ea11-a812-000d3a8b3ec6",
          completefinalproposal: false,
          msdyn_opportunityscore: null,
          msdyn_scorehistory: null,
          _msdyn_predictivescoreid_value: null,
          actualvalue_base: null,
          msdyn_opportunityscoretrend: null,
          _msdyn_segmentid_value: null,
          budgetstatus: null,
          _accountid_value: null,
          finaldecisiondate: null,
          closeprobability: null,
          _slainvokedid_value: null,
          msdyn_similaropportunities: null,
          msdyn_opportunitygrade: null,
          quotecomments: null,
          timeline: null,
          qualificationcomments: null,
          _contactid_value: null,
          _campaignid_value: null,
          stageid: null,
          lastonholdtime: null,
          need: null,
          purchaseprocess: null,
          _modifiedonbehalfby_value: null,
          stepid: null,
          freightamount_base: null,
          description: null,
          discountamount_base: null,
          onholdtime: null,
          schedulefollowup_qualify: null,
          importsequencenumber: null,
          utcconversiontimezonecode: null,
          discountamount: null,
          salesstage: null,
          _createdonbehalfby_value: null,
          traversedpath: null,
          _originatingleadid_value: null,
          customerpainpoints: null,
          emailaddress: null,
          _owningteam_value: null,
          _msdyn_opportunitykpiid_value: null,
          proposedsolution: null,
          scheduleproposalmeeting: null,
          timespentbymeonemailandmeetings: null,
          purchasetimeframe: null,
          teamsfollowed: null,
          _pricelevelid_value: null,
          overriddencreatedon: null,
          initialcommunication: null,
          schedulefollowup_prospect: null,
          currentsituation: null,
          msdyn_scorereasons: null,
          freightamount: null,
          actualclosedate: null,
          actualvalue: null,
          discountpercentage: null,
          _slaid_value: null,
          currency: "EUR",
        },
      ],
    }),
    getContactsById: () => ({
      value: [
        {
          "@odata.etag": 'W/"5350374"',
          customertypecode: 1,
          mobilephone: "619-555-0129",
          merged: false,
          gendercode: 2,
          territorycode: 1,
          emailaddress1: "alex@treyresearch.net",
          haschildrencode: 1,
          exchangerate: 1,
          preferredappointmenttimecode: 1,
          isbackofficecustomer: false,
          modifiedon: "2024-01-16T14:01:32Z",
          msdyn_orgchangestatus: 0,
          _owninguser_value: "29c3a361-4b9c-ee11-be36-000d3abf077e",
          _msdyn_contactkpiid_value: "80ac35a0-01af-ea11-a812-000d3a8b3ec6",
          adx_profilealert: false,
          address1_composite:
            "789 3rd St\r\nSan Francisco, California 94158\r\nUnited States",
          lastname: "Baker",
          donotpostalmail: false,
          telephone1: "619-555-0127",
          marketingonly: false,
          donotphone: false,
          preferredcontactmethodcode: 1,
          adx_identity_locallogindisabled: false,
          educationcode: 1,
          _ownerid_value: "29c3a361-4b9c-ee11-be36-000d3abf077e",
          entityimage:
            "/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAB2AHYDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD3jFLRRQIKKKa7pHGzuwVEG5mPQCmAk00dvC000ixxoMs7HAArzHxN8YLSwd7fR4hcOOPOk+7+A71yHxB8fT67dtY2DsthGxCgf8tP9o151KzseDknqaxlPsdMKSSuzr7z4oeI7yUl71lU9Ej+WmDx3rcq4mu5n4xkt0rh5GdDt3EeoWprcNnjePfOanUqy7Ho2nfEbVbC5S7uruWWIHZjqfyr07SPihoWo7EllMLtx81fN99JJHb7W/ix0qnD5pYEOQRVptGbjFs+0IZ4riMSQuroehBp9fOPgX4i3vh6+jttQYyWTHacn7o9q+ioZ47mCOeFw8cih0YdwatO5lKNh9FFJVEhRRRQA6iiigArzD4seKJLW3XQLFyJJl3XTqeVTsv416Re3UdjZT3cp+SFC5/CvmrxJqcl1dXGo3Dbri4l+VfUnp+VRN9DWktbsxRbtI7KvAH3jVeYJF8iDNaMkgtbRE6yP2HVjXRaD8P7nU4VutQ3Rxt8wj7tWDdtzqWux52z7m+XJPsKvWVtLKQVjf8AKvXIfB+m2g2i2U/UVaj0Ozh+5Eo/CsnW8i/Y+Z5Jq9lKkELGIrt65FU4rcr8xw6njK/w17BqWhRXduy7B06V5xqWlSaVcMSCE9R/WqVS+hPsrO5nrErDy5Vyp6EV7d8INfe80WfRLly0+nnMZPeI9PyNeMEoQpJBRujDsa6bwJq/9jeNLGRztSVvs8voVbgH88VpCWpFWF4n0VRQeKaTXScQhNFRs3NFMRZooopDOQ+IupfYvDgtlbD3b7f+Ajk/0r50vbtJ9XeRz/o9oMgerV6z8WdSJ1IwhvktYMYz/E3J/pXiulwyaxrVtYxctPLz9c/0FYyep0wVoo9P+HXhYX8n9uaom7/nhE3RR616e8oVcKAAKp2lqmn6fFZ2yA+Wm3k4H1NZd1qV5acSWsbj/Yk/xrncjdRuX7hwTUPBqrbX/wBu48l42A6MKsM6xrk9utYt3N0rD8DbXPa/piXdu/y84q+2qySNiCykI9WOBUm26nQtJAm30VsmjzFseI3Aaw1CWzk/1bdPY1YWZjEjqcSJ8ufccg1r+P8ATBCReIMbW5rm7ecPDvHQ4NdMXdXMHdSsfV/h/Ul1jw7p+oKc+fArH/exz+tX2PFcD8Hr/wC1eC3ti2Ws7l0/4C2GH8zXeOeK6o6o4ZKzsQSNzRUch+aimI06UdfxpKr39ytpp9xcscCONm/SgaPnj4j6ibjUNTk353XW0Y9B/wDqrD+FNosniyGZhkqjMM9uKb4jkM9rMzffafcefVc0fDK+Ft4std3CSBo8/UYH61zS2Z1pao9zvJpoLZ2hAMhHGfWuA1nS9XlEbm9d33kvsOAF9q9JuYFktDnqKxEh/eEYyKwb5TpjFNGf4Tiusus5Zo1YqhfrjtWnffuzIF5I6VqafAgTKAEe1UrtFeWQH1qZR0BS1ON1RdYuBIttK8IVlCbP4l7mrWlzaxaTBJn862IHzP8AfB71tldvy4BxSrCHIxST6FcmtzmPHFl9p8PXkuPmEe78q8es3KKUPrXuvjAJB4T1Bm/54kD6ngV4GkmJUTocit6WzRhWtdHunwOvMT6xaM3DiORR7jIP6GvXpDXhXwZm2eIroeqIfwyVP/oQr3SU8V0w2OKp8RTkPNFMkPNFUQbVc743ultvC11k43oVH+fxroq4T4ozbdDSLOMsCfz/APrUpuyLgrySPBtWbzDcoOu8H9MVW8Hxr5kswlRZIXUqpOCeeopbh2XVLiF+o4P1Fc1exSW93Misy4PY4yKxtdWOnm5Xc+rGuhJaRupB8xAwx3yKx5ZJJrgW6ZGetUfAmojVfAujXIO6SBfs0v1X5f5YNT61dXulXscllYm8bDO8Stgke1ckk72Oqm9Lo6KCZLOGNDGeBjI6Vm3d3BFMzMc57DvVuR7i8sEure33xum7g8j2PvWRJZ6kZsfY8Ybbk/TNXJS2CKi9Wx83znegwuM80+BweelUNVu7mwhji+ziS5m4WIPz9T6Vcsw0tvFLIMOVG4D1rJppl30Od+INxGuhQwyyrGk1woJJ6gAmvEyI21SQxNviV/kJ7ivQPjHfqZtN01GyUDzOPr8o/rXnmnr836V1017tzjqSvKx6h8JZxD4weM9XtsD6hlNfQMp4r5j8A3n2TxtpT7tqSXAicn+6zAf4V9NTcZreGxzVV7xRlbDUVHcnkUVRB0NedfEpvNlt4DnZsy34sF/rXoteZ/EK5ENzLJKpMcLws2DzsUF2/pUz2Kp/EeIXKO17c3HTdJJ19mApninSprK8USxbZFjQnA4ZSoII/CuifTf+JFZ6g4J32rzOOnLyEj9AaPGN2k+q2cTShk+wxRoR1+VRk/iSfyqLWRqpXdhnwq186XqtxpE0n+h3mJIyeiuOM/iP5V7UIN99Dc9cKVNfNmnK9pqqYH3X4/wr3Hw/rzCBIrklgB8r9/xrmqWUrnTTvy2OhvRMkbm2fyyeoHFYRl1Z2KNcsAWzndXQSXEcse5GBB9KzX2UpSfRm1PbVENvZRws8jHfK33mNMvry30vT5bu5kEUMKlmY1PPdw20WScn0FeT/E7V7i5sYoMlYjJ9we3rUxXNKxM5NJs4XxFrMmv67cahJkCQ4RT/AAoOgpbFNqFz2rKj+ZgB1JrdgTbat9cV2PRWOKLu7s0NGVm1SzQPsYyIFb+6S3B/OvqWzvPt+l212eGliDOPRv4h+ea+ULWUw6ijjrGysPwwa+ndAmDWd1Ev3EuDJH/uSKJB+rN+VOmTVJrxsMKKgvnw4oq7mR11ePfFG5eSe8tIBmSWGTcf7qjYrforV6JqHjPw/pm7z9SiLL/DH85/SvEvEnj62uNc1iaK0kljuLdre1Ljbt3fec/h/OlIqCNPWo4LDwM0TyIrGC1hUHqF+zlj+OWryea/lvtXjmlbLnCj2UDAFS6lq9/qSqk9xJJGu3CnpwoUfoAKgsLVhP5zjgdKktI0yjJPHMo54yK9K8PXCXNujr16Mvoa8/s4DeTlPmCZAJxXWacJNKvkdlKwy+vY1z1qbcbnTSqpSsd5GibO4+lI8Sj+Jj+NNhlEsYYdDUgGTXIdJRuI9wOOgry3x8m64tl/2m/lXrki/u2rzHxdCLjVo0Xny42Y/mK1o35kZVn7jPNli8m4Yen3a3Ih/o8K92+aql/ZbblXGQGFW4DvuI07KMcfSuyVzlgV1b/TJPrivonwVf8An6fZZOfOsUY/VTj/ANmP5V86sji8kI5U8/SvUfhr4jiW6stNuW2svmxxuTxtfDAf99L/AOPU46Ez1R6TqkuJQKKo6lNuueCOlFUYHQf2dZIoEdrAijsIxXnvj9rWSSOxFpEvG5nCgH8KKKCjziTR4xKArYycVoabpMRkw2Gx0yKKKaQ2zr7XSoIdpIBI6YFP1OBJU2YxtB5ooqpbExbuTaDdOVMMnzbDjNb3Q0UV5T3PV7FXUJzDauwHSvPCv2u4urh/vswUewAzRRWtD4jKv8Bj6jYI8G7OCj4/OqNpaLBeRjOc8n8qKK62ckNySw0c3+qfZ0kVN8mMkfSu3m+GDQwK0GoBZeuSDiiik9h9TprHSdQgsIxc3ccrr8oIB6UUUUyD/9k=",
          entityimage_timestamp: 638384060887937800,
          adx_identity_logonenabled: false,
          customersizecode: 1,
          firstname: "Alex",
          adx_identity_lockoutenabled: false,
          entityimage_url:
            "/Image/download.aspx?Entity=contact&Attribute=entityimage&Id=80ac35a0-01af-ea11-a812-000d3a8b3ec6&Timestamp=638384060887937791",
          yomifullname: "Alex Baker",
          address2_addresstypecode: 1,
          adx_profileisanonymous: false,
          donotemail: false,
          address2_shippingmethodcode: 1,
          fullname: "Alex Baker",
          timezoneruleversionnumber: 4,
          address1_addressid: "8658a33b-9954-49a7-bb76-cdf9d76318dd",
          msdyn_gdproptout: false,
          address2_freighttermscode: 1,
          statuscode: 1,
          createdon: "2023-12-17T10:34:48Z",
          creditlimit: 10000,
          address1_stateorprovince: "California",
          donotsendmm: false,
          donotfax: false,
          leadsourcecode: 1,
          jobtitle: "Cafeteria Manager",
          address1_country: "United States",
          versionnumber: 5350374,
          adx_confirmremovepassword: false,
          address1_line1: "789 3rd St",
          birthdate: "1985-02-26",
          adx_identity_emailaddress1confirmed: false,
          msdyn_isminor: false,
          _transactioncurrencyid_value: "dbce9d1c-c29c-ee11-be36-000d3abf077e",
          msdyn_isminorwithparentalconsent: false,
          address3_addressid: "236f8540-6483-4078-bfff-94222160a9e8",
          donotbulkemail: false,
          creditonhold: false,
          familystatuscode: 1,
          creditlimit_base: 10000,
          adx_identity_twofactorenabled: false,
          _modifiedby_value: "29c3a361-4b9c-ee11-be36-000d3abf077e",
          followemail: true,
          shippingmethodcode: 1,
          _createdby_value: "29c3a361-4b9c-ee11-be36-000d3abf077e",
          address1_city: "San Francisco",
          donotbulkpostalmail: false,
          _parentcustomerid_value: "a4cea450-cb0c-ea11-a813-000d3a1b1223",
          fax: "619-555-0128",
          contactid: "80ac35a0-01af-ea11-a812-000d3a8b3ec6",
          msdyn_disablewebtracking: false,
          msdyn_isassistantinorgchart: false,
          adx_identity_mobilephoneconfirmed: false,
          participatesinworkflow: false,
          statecode: 0,
          _owningbusinessunit_value: "37bca361-4b9c-ee11-be36-000d3abf077e",
          address2_addressid: "64bf2d39-7fa5-44e3-b2de-ebac40a71bb7",
          address1_postalcode: "94158",
          entityimageid: "8a1c0be1-c79c-ee11-be37-000d3aaae2d6",
          telephone3: null,
          businesscardattributes: null,
          address1_shippingmethodcode: null,
          _defaultpricelevelid_value: null,
          adx_profilealertinstructions: null,
          _preferredequipmentid_value: null,
          nickname: null,
          address1_freighttermscode: null,
          address3_upszone: null,
          annualincome_base: null,
          anniversary: null,
          address1_upszone: null,
          adx_profilelastactivity: null,
          websiteurl: null,
          address2_city: null,
          _slainvokedid_value: null,
          address1_postofficebox: null,
          importsequencenumber: null,
          address3_longitude: null,
          preferredappointmentdaycode: null,
          utcconversiontimezonecode: null,
          overriddencreatedon: null,
          aging90: null,
          stageid: null,
          address3_primarycontactname: null,
          address1_latitude: null,
          address1_utcoffset: null,
          home2: null,
          adx_createdbyipaddress: null,
          yomifirstname: null,
          _masterid_value: null,
          address3_shippingmethodcode: null,
          lastonholdtime: null,
          address3_stateorprovince: null,
          address2_fax: null,
          address3_telephone3: null,
          address3_telephone2: null,
          address3_telephone1: null,
          msdyn_portaltermsagreementdate: null,
          governmentid: null,
          address2_line1: null,
          address1_telephone3: null,
          address1_telephone2: null,
          address1_telephone1: null,
          address2_postofficebox: null,
          emailaddress2: null,
          ftpsiteurl: null,
          address2_latitude: null,
          processid: null,
          emailaddress3: null,
          address2_composite: null,
          traversedpath: null,
          address3_name: null,
          spousesname: null,
          address3_postofficebox: null,
          adx_identity_securitystamp: null,
          address2_line2: null,
          adx_publicprofilecopy: null,
          aging30_base: null,
          teamsfollowed: null,
          adx_identity_username: null,
          address1_addresstypecode: null,
          managerphone: null,
          address2_stateorprovince: null,
          address2_postalcode: null,
          _msa_managingpartnerid_value: null,
          adx_organizationname: null,
          managername: null,
          aging60: null,
          address3_postalcode: null,
          adx_identity_accessfailedcount: null,
          adx_profilealertdate: null,
          address3_utcoffset: null,
          address2_telephone3: null,
          address2_telephone2: null,
          address2_telephone1: null,
          numberofchildren: null,
          address2_upszone: null,
          _owningteam_value: null,
          address2_line3: null,
          timespentbymeonemailandmeetings: null,
          department: null,
          businesscard: null,
          mspp_userpreferredlcid: null,
          adx_identity_newpassword: null,
          address2_longitude: null,
          suffix: null,
          _modifiedonbehalfby_value: null,
          address1_line2: null,
          paymenttermscode: null,
          address1_county: null,
          _preferredsystemuserid_value: null,
          accountrolecode: null,
          assistantname: null,
          address1_fax: null,
          adx_identity_passwordhash: null,
          _createdonbehalfby_value: null,
          annualincome: null,
          _accountid_value: null,
          adx_identity_lockoutenddate: null,
          address2_name: null,
          business2: null,
          _modifiedbyexternalparty_value: null,
          address2_utcoffset: null,
          address3_composite: null,
          adx_modifiedbyusername: null,
          _originatingleadid_value: null,
          _preferredserviceid_value: null,
          _slaid_value: null,
          childrensnames: null,
          address2_county: null,
          address3_city: null,
          aging30: null,
          externaluseridentifier: null,
          adx_timezone: null,
          address1_line3: null,
          _parentcontactid_value: null,
          assistantphone: null,
          address3_addresstypecode: null,
          onholdtime: null,
          _createdbyexternalparty_value: null,
          address3_county: null,
          employeeid: null,
          subscriptionid: null,
          company: null,
          callback: null,
          lastusedincampaign: null,
          address3_line3: null,
          adx_profilemodifiedon: null,
          adx_createdbyusername: null,
          telephone2: null,
          address3_freighttermscode: null,
          yomilastname: null,
          address3_fax: null,
          description: null,
          address3_line1: null,
          adx_preferredlcid: null,
          address3_line2: null,
          adx_identity_lastsuccessfullogin: null,
          yomimiddlename: null,
          aging90_base: null,
          adx_modifiedbyipaddress: null,
          address1_name: null,
          address1_primarycontactname: null,
          address1_longitude: null,
          msdyn_decisioninfluencetag: null,
          address2_primarycontactname: null,
          middlename: null,
          address3_latitude: null,
          salutation: null,
          aging60_base: null,
          pager: null,
          address3_country: null,
          address2_country: null,
          currency: "EUR",
        },
      ],
    }),
    getFirst5TasksByContactId: () => ({
      "@odata.context":
        "https://orgefaf8628.api.crm4.dynamics.com/api/data/v9.2/$metadata#tasks",
      value: [
        {
          "@odata.etag": 'W/"4850486"',
          scheduledstart: "2024-01-18T08:00:00Z",
          scheduleddurationminutes: 0,
          _regardingobjectid_value: "80ac35a0-01af-ea11-a812-000d3a8b3ec6",
          statuscode: 2,
          description: "stuff",
          createdon: "2024-01-09T02:19:17Z",
          statecode: 0,
          isbilled: false,
          subject: "tasks",
          _ownerid_value: "29c3a361-4b9c-ee11-be36-000d3abf077e",
          modifiedon: "2024-01-09T02:19:17Z",
          versionnumber: 4850486,
          prioritycode: 1,
          timezoneruleversionnumber: 4,
          isregularactivity: true,
          scheduledend: "2024-01-18T08:00:00Z",
          _modifiedby_value: "29c3a361-4b9c-ee11-be36-000d3abf077e",
          activitytypecode: "task",
          isworkflowcreated: false,
          _createdby_value: "29c3a361-4b9c-ee11-be36-000d3abf077e",
          _owningbusinessunit_value: "37bca361-4b9c-ee11-be36-000d3abf077e",
          _owninguser_value: "29c3a361-4b9c-ee11-be36-000d3abf077e",
          activityid: "4721ed7c-95ae-ee11-a569-0022488293fd",
          actualdurationminutes: 30,
          onholdtime: null,
          _slaid_value: null,
          leftvoicemail: null,
          seriesid: null,
          instancetypecode: null,
          actualstart: null,
          exchangeitemid: null,
          _transactioncurrencyid_value: null,
          stageid: null,
          descriptionblobid: null,
          formattedscheduledend: null,
          deliveryprioritycode: null,
          postponeactivityprocessinguntil: null,
          senton: null,
          _serviceid_value: null,
          activityadditionalparams: null,
          _modifiedonbehalfby_value: null,
          exchangerate: null,
          formattedscheduledstart: null,
          actualend: null,
          descriptionblobid_name: null,
          community: null,
          _slainvokedid_value: null,
          utcconversiontimezonecode: null,
          ismapiprivate: null,
          processid: null,
          _createdonbehalfby_value: null,
          exchangeweblink: null,
          lastonholdtime: null,
          deliverylastattemptedon: null,
          _sendermailboxid_value: null,
          traversedpath: null,
          sortdate: null,
          _owningteam_value: null,
          percentcomplete: null,
          overriddencreatedon: null,
          subcategory: null,
          category: null,
          crmtaskassigneduniqueid: null,
          importsequencenumber: null,
          subscriptionid: null,
        },
      ],
    }),
    getFirst5CallsByContactId: () => ({
      "@odata.context":
        "https://orgefaf8628.api.crm4.dynamics.com/api/data/v9.2/$metadata#phonecalls",
      value: [
        {
          "@odata.etag": 'W/"4850561"',
          scheduledstart: "2024-01-17T08:00:00Z",
          scheduleddurationminutes: 0,
          _regardingobjectid_value: "80ac35a0-01af-ea11-a812-000d3a8b3ec6",
          statuscode: 1,
          description: "some phone things",
          leftvoicemail: false,
          createdon: "2024-01-09T02:27:29Z",
          statecode: 0,
          isbilled: false,
          subject: "phone stuff",
          directioncode: true,
          _ownerid_value: "29c3a361-4b9c-ee11-be36-000d3abf077e",
          phonenumber: "+351934575689",
          modifiedon: "2024-01-09T02:27:29Z",
          versionnumber: 4850561,
          prioritycode: 0,
          timezoneruleversionnumber: 4,
          isregularactivity: true,
          scheduledend: "2024-01-17T08:00:00Z",
          _modifiedby_value: "29c3a361-4b9c-ee11-be36-000d3abf077e",
          activitytypecode: "phonecall",
          isworkflowcreated: false,
          _createdby_value: "29c3a361-4b9c-ee11-be36-000d3abf077e",
          _owningbusinessunit_value: "37bca361-4b9c-ee11-be36-000d3abf077e",
          _owninguser_value: "29c3a361-4b9c-ee11-be36-000d3abf077e",
          activityid: "58c328a2-96ae-ee11-a569-0022488293fd",
          actualdurationminutes: 30,
          onholdtime: null,
          _slaid_value: null,
          seriesid: null,
          instancetypecode: null,
          actualstart: null,
          exchangeitemid: null,
          _transactioncurrencyid_value: null,
          stageid: null,
          descriptionblobid: null,
          formattedscheduledend: null,
          deliveryprioritycode: null,
          postponeactivityprocessinguntil: null,
          senton: null,
          _serviceid_value: null,
          activityadditionalparams: null,
          _modifiedonbehalfby_value: null,
          exchangerate: null,
          formattedscheduledstart: null,
          actualend: null,
          descriptionblobid_name: null,
          community: null,
          _slainvokedid_value: null,
          utcconversiontimezonecode: null,
          ismapiprivate: null,
          processid: null,
          _createdonbehalfby_value: null,
          exchangeweblink: null,
          lastonholdtime: null,
          deliverylastattemptedon: null,
          _sendermailboxid_value: null,
          traversedpath: null,
          sortdate: null,
          _owningteam_value: null,
          overriddencreatedon: null,
          subcategory: null,
          category: null,
          importsequencenumber: null,
          subscriptionid: null,
        },
      ],
    }),
    getFirst5AppointmentsByContactId: () => ({
      "@odata.context":
        "https://orgefaf8628.api.crm4.dynamics.com/api/data/v9.2/$metadata#appointments",
      value: [
        {
          "@odata.etag": 'W/"4850503"',
          scheduledstart: "2024-01-09T02:30:00Z",
          scheduleddurationminutes: 30,
          onlinemeetingjoinurl:
            'https://teams.microsoft.com/l/meetup-join/19:meeting_ZTg1NGI5NmQtOWM1MC00ZTFiLWExM2QtMWY4MWE2MzUxNjY3@thread.v2/0?context={"Tid":"98784d73-29ca-44e6-8569-5a1a32a9cfa3","Oid":"6bdbfd8e-4467-4872-b6af-4978f0a8624c"}',
          _regardingobjectid_value: "80ac35a0-01af-ea11-a812-000d3a8b3ec6",
          statuscode: 1,
          isbilled: false,
          activitytypecode: "appointment",
          description:
            '<div data-wrapper="true" dir="ltr" style="font-size:9pt;font-family:\'Segoe UI\',\'Helvetica Neue\',sans-serif;"><div>this is a meeting so ya</div></div><div style="width:100%;">\r\n    <span style="white-space:nowrap;color:#5F5F5F;opacity:.36;">________________________________________________________________________________</span>\r\n</div>\r\n \r\n <div class="me-email-text" style="color:#252424;font-family:\'Segoe UI\',\'Helvetica Neue\',Helvetica,Arial,sans-serif;" lang="en-US">\r\n    <div style="margin-top: 24px; margin-bottom: 20px;">\r\n        <span style="font-size: 24px; color:#252424">Microsoft Teams meeting</span>\r\n    </div>\r\n    <div style="margin-bottom: 20px;">\r\n        <div style="margin-top: 0px; margin-bottom: 0px; font-weight: bold">\r\n          <span style="font-size: 14px; color:#252424">Join on your computer, mobile app or room device</span>\r\n        </div>\r\n        <a class="me-email-headline" style="font-size: 14px;font-family:\'Segoe UI Semibold\',\'Segoe UI\',\'Helvetica Neue\',Helvetica,Arial,sans-serif;text-decoration: underline;color: #6264a7;" href="https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZTg1NGI5NmQtOWM1MC00ZTFiLWExM2QtMWY4MWE2MzUxNjY3%40thread.v2/0?context=%7b%22Tid%22%3a%2298784d73-29ca-44e6-8569-5a1a32a9cfa3%22%2c%22Oid%22%3a%226bdbfd8e-4467-4872-b6af-4978f0a8624c%22%7d" target="_blank" rel="noreferrer noopener">Click here to join the meeting</a>\r\n    </div>\r\n    <div style="margin-bottom:20px; margin-top:20px">\r\n    <div style="margin-bottom:4px">\r\n        <span data-tid="meeting-code" style="font-size: 14px; color:#252424;">\r\n            Meeting ID: <span style="font-size:16px; color:#252424;">387 764 880 558</span>\r\n       </span>\r\n        \r\n        <div style="font-size: 14px;"><a class="me-email-link" style="font-size: 14px;text-decoration: underline;color: #6264a7;font-family:\'Segoe UI\',\'Helvetica Neue\',Helvetica,Arial,sans-serif;" target="_blank" href="https://www.microsoft.com/en-us/microsoft-teams/download-app" rel="noreferrer noopener">\r\n        Download Teams</a> | <a class="me-email-link" style="font-size: 14px;text-decoration: underline;color: #6264a7;font-family:\'Segoe UI\',\'Helvetica Neue\',Helvetica,Arial,sans-serif;" target="_blank" href="https://www.microsoft.com/microsoft-teams/join-a-meeting" rel="noreferrer noopener">Join on the web</a></div>\r\n    </div>\r\n </div>\r\n    \r\n      \r\n    \r\n    \r\n    \r\n    <div style="margin-bottom: 24px;margin-top: 20px;">\r\n        <a class="me-email-link" style="font-size: 14px;text-decoration: underline;color: #6264a7;font-family:\'Segoe UI\',\'Helvetica Neue\',Helvetica,Arial,sans-serif;" target="_blank" href="https://aka.ms/JoinTeamsMeeting" rel="noreferrer noopener">Learn More</a>  | <a class="me-email-link" style="font-size: 14px;text-decoration: underline;color: #6264a7;font-family:\'Segoe UI\',\'Helvetica Neue\',Helvetica,Arial,sans-serif;" target="_blank" href="https://teams.microsoft.com/meetingOptions/?organizerId=6bdbfd8e-4467-4872-b6af-4978f0a8624c&tenantId=98784d73-29ca-44e6-8569-5a1a32a9cfa3&threadId=19_meeting_ZTg1NGI5NmQtOWM1MC00ZTFiLWExM2QtMWY4MWE2MzUxNjY3@thread.v2&messageId=0&language=en-US" rel="noreferrer noopener">Meeting options</a> \r\n      </div>\r\n</div>\r\n<div style="font-size: 14px; margin-bottom: 4px;font-family:\'Segoe UI\',\'Helvetica Neue\',Helvetica,Arial,sans-serif;">\r\n\r\n</div>\r\n<div style="font-size: 12px;">\r\n\r\n</div>\r\n\r\n</div>\r\n<div style="width:100%;">\r\n    <span style="white-space:nowrap;color:#5F5F5F;opacity:.36;">________________________________________________________________________________</span>\r\n</div>',
          createdon: "2024-01-09T02:23:32Z",
          onlinemeetingchatid:
            "19:meeting_ZTg1NGI5NmQtOWM1MC00ZTFiLWExM2QtMWY4MWE2MzUxNjY3@thread.v2",
          statecode: 0,
          location: "Middle of nowhere",
          subject: "meetingg",
          onlinemeetingtype: 1,
          _ownerid_value: "29c3a361-4b9c-ee11-be36-000d3abf077e",
          isunsafe: 0,
          modifiedon: "2024-01-09T02:23:32Z",
          versionnumber: 4850503,
          prioritycode: 2,
          isdraft: false,
          timezoneruleversionnumber: 4,
          isregularactivity: true,
          isalldayevent: false,
          ismapiprivate: false,
          _modifiedby_value: "29c3a361-4b9c-ee11-be36-000d3abf077e",
          isonlinemeeting: true,
          instancetypecode: 0,
          onlinemeetingid:
            "MSo2YmRiZmQ4ZS00NDY3LTQ4NzItYjZhZi00OTc4ZjBhODYyNGMqMCoqMTk6bWVldGluZ19aVGcxTkdJNU5tUXRPV00xTUMwMFpURmlMV0V4TTJRdE1XWTRNV0UyTXpVeE5qWTNAdGhyZWFkLnYy",
          activityadditionalparams:
            '{"scheduledstartformatted":"1/9/2024 2:30 AM","scheduledendformatted":"1/9/2024 3:00 AM"}',
          isworkflowcreated: false,
          _createdby_value: "29c3a361-4b9c-ee11-be36-000d3abf077e",
          attachmenterrors: 0,
          _owningbusinessunit_value: "37bca361-4b9c-ee11-be36-000d3abf077e",
          _owninguser_value: "29c3a361-4b9c-ee11-be36-000d3abf077e",
          activityid: "43148013-96ae-ee11-a569-0022488293fd",
          scheduledend: "2024-01-09T03:00:00Z",
          actualdurationminutes: null,
          onholdtime: null,
          _slaid_value: null,
          leftvoicemail: null,
          seriesid: null,
          actualstart: null,
          exchangeitemid: null,
          _transactioncurrencyid_value: null,
          stageid: null,
          descriptionblobid: null,
          formattedscheduledend: null,
          deliveryprioritycode: null,
          postponeactivityprocessinguntil: null,
          senton: null,
          _serviceid_value: null,
          _modifiedonbehalfby_value: null,
          exchangerate: null,
          formattedscheduledstart: null,
          actualend: null,
          descriptionblobid_name: null,
          community: null,
          _slainvokedid_value: null,
          utcconversiontimezonecode: null,
          processid: null,
          _createdonbehalfby_value: null,
          exchangeweblink: null,
          lastonholdtime: null,
          deliverylastattemptedon: null,
          _sendermailboxid_value: null,
          traversedpath: null,
          sortdate: null,
          _owningteam_value: null,
          subscriptionid: null,
          originalstartdate: null,
          overriddencreatedon: null,
          importsequencenumber: null,
          outlookownerapptid: null,
          globalobjectid: null,
          category: null,
          modifiedfieldsmask: null,
          subcategory: null,
        },
      ],
    }),
    getCurrencies: () => [
      {
        "@odata.etag": 'W/"4395615"',
        _organizationid_value: "f82701d9-74a9-ee11-be32-000d3a45fb59",
        currencyname: "Euro",
        currencysymbol: "€",
        _createdonbehalfby_value: "80c5cd80-b1d6-4269-838f-b201cf187868",
        statecode: 0,
        statuscode: 1,
        _modifiedonbehalfby_value: "80c5cd80-b1d6-4269-838f-b201cf187868",
        _createdby_value: "80c5cd80-b1d6-4269-838f-b201cf187868",
        isocurrencycode: "EUR",
        _modifiedby_value: "80c5cd80-b1d6-4269-838f-b201cf187868",
        createdon: "2023-12-17T09:53:24Z",
        versionnumber: 4395615,
        exchangerate: 1,
        modifiedon: "2023-12-17T09:53:24Z",
        currencyprecision: 2,
        transactioncurrencyid: "dbce9d1c-c29c-ee11-be36-000d3abf077e",
        entityimage_url: null,
        overriddencreatedon: null,
        importsequencenumber: null,
        entityimage_timestamp: null,
        entityimageid: null,
        entityimage: null,
      },
    ],
  };
});

describe("Main", () => {
  test("Main page should show all data correctly", async () => {
    const { getByText } = renderPage();

    const email = await waitFor(() => getByText(/Alex@treyresearch.net/i));

    const creditLimit = await waitFor(() => getByText(/€10,000.00/i));

    const appointmentPriority = await waitFor(() => getByText(/High/i));

    await waitFor(() => {
      [email, creditLimit, appointmentPriority].forEach((el) => {
        expect(el).toBeInTheDocument();
      });
    });
  });

  afterEach(() => {
    jest.clearAllMocks();

    cleanup();
  });
});
